// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-browser-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_browser_info_default = defineTool({
  name: "get_browser_info",
  title: "Get browser info",
  description: "Return version, channel, engine and build details for the Aether browser shell.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "Aether",
      tagline: "A Chromium-inspired browser shell built with React",
      version: "152.0.8100.0",
      channel: "Canary",
      buildDate: "July 13, 2026",
      engine: "Blink (simulated)",
      javascript: "V8 12.7",
      userAgent: "Mozilla/5.0 Aether/152 Canary"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-themes.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
var THEMES = [
  { id: "modern", name: "Modern", description: "Current Chrome-style chrome with 12px rounded tabs." },
  { id: "legacy-2010", name: "Legacy 2010", description: "Early Chrome look with 6px tab corners." },
  { id: "legacy-2016", name: "Legacy 2016", description: "Flat Material era with nearly square 2px tabs." },
  { id: "legacy-2018", name: "Legacy 2018", description: "Chrome 69 refresh with 6px rounded tabs." },
  { id: "legacy-2021", name: "Legacy 2021", description: "Chrome 90 era with 8px rounded tabs." }
];
var list_themes_default = defineTool2({
  name: "list_themes",
  title: "List themes",
  description: "List the chrome themes (eras) Aether can be styled with.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(THEMES, null, 2) }],
    structuredContent: { themes: THEMES }
  })
});

// src/lib/mcp/tools/list-flags.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
var FLAGS = [
  { id: "compact-tabs", name: "Compact tabs", description: "Reduce tab height for a denser look.", default: false },
  { id: "rounded-omnibox", name: "Extra rounded omnibox", description: "Use a more pill-shaped address bar.", default: true },
  { id: "show-loading-bar", name: "Show loading progress bar", description: "Animated bar at the top of the webview while loading.", default: true },
  { id: "experimental-glass", name: "Experimental glass UI", description: "Adds a subtle backdrop blur to chrome surfaces.", default: false }
];
var list_flags_default = defineTool3({
  name: "list_flags",
  title: "List experimental flags",
  description: "List the experimental flags available on the aether://flags page, with their default values.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(FLAGS, null, 2) }],
    structuredContent: { flags: FLAGS }
  })
});

// src/lib/mcp/tools/list-internal-pages.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
var PAGES = [
  { url: "aether://newtab", title: "New Tab" },
  { url: "aether://settings", title: "Settings" },
  { url: "aether://flags", title: "Experiments" },
  { url: "aether://about", title: "About Aether" },
  { url: "aether://downloads", title: "Downloads" },
  { url: "aether://passwords", title: "Password Manager" },
  { url: "aether://extensions", title: "Extensions" }
];
var list_internal_pages_default = defineTool4({
  name: "list_internal_pages",
  title: "List internal pages",
  description: "List the built-in aether:// pages and their titles.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(PAGES, null, 2) }],
    structuredContent: { pages: PAGES }
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "remix-of-remix-of-public",
  title: "Remix of Remix of public",
  version: "0.1.0",
  instructions: "Read-only tools describing the Aether browser shell: build info, available chrome themes, experimental flags, and built-in aether:// pages.",
  tools: [get_browser_info_default, list_themes_default, list_flags_default, list_internal_pages_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
